# Site settings
author: Molly Brown
title: Learning Data Science
header-img: img/home-bg.png
email: mollytjbrown@gmail.com
copyright_name: Molly Brown
description: > # this means to ignore newlines until "baseurl:"
  a Beginner's Perspective 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mollytjbrown

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
